on: [push]
name: Tests
jobs:
    setup-and-tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Build containers
                run: docker-compose build

            -   name: Composer install
                run: docker-compose run --rm -T php composer install --no-interaction --no-progress

            -   name: Run Tests
                run: docker-compose run --rm -T php vendor/bin/phpunit
